workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Add Android platform
        script: |
          flutter create . --platforms android
      - name: Build APK
        script: flutter build apk --release --no-tree-shake-icons --dart-define=GROQ_API_KEY=$GROQ_API_KEY
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - ticallcenter@gmail.com
        notify:
          success: true
          failure: true
